-- Run this in Supabase SQL Editor for development.
-- For production, replace the public policies with authenticated, user-scoped policies.

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  room text,
  admission_date timestamptz,
  status text,
  medical_history text,
  care_plan text,
  created_at timestamptz default now()
);

create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  role text,
  phone text,
  status text,
  created_at timestamptz default now()
);

create table if not exists public.meals (
  id bigint generated by default as identity primary key,
  meal_type text,
  menu text,
  updated_date timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.medications (
  id bigint generated by default as identity primary key,
  client_id bigint,
  medication_name text,
  dosage text,
  schedule text,
  status text,
  created_at timestamptz default now()
);

create table if not exists public.progress_notes (
  id bigint generated by default as identity primary key,
  client_id bigint,
  staff_name text,
  note text,
  recorded_at timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  client_name text,
  reason_for_visit text,
  location text,
  contact_information text,
  appointment_datetime timestamptz,
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.finance_records (
  id bigint generated by default as identity primary key,
  entry_type text,
  category text,
  client_name text,
  caregiver_name text,
  amount numeric,
  month text,
  notes text,
  created_at timestamptz default now()
);

-- The app probes these tables during startup, so create them even if empty.
create table if not exists public.policy_updates (id bigint generated by default as identity primary key, title text, effective_date timestamptz, details text, created_at timestamptz default now());
create table if not exists public.training_records (id bigint generated by default as identity primary key, title text, due_date timestamptz, status text, details text, created_at timestamptz default now());
create table if not exists public.staff_schedules (id bigint generated by default as identity primary key, caregiver_name text, shift text, status text, days text, notes text, created_at timestamptz default now());

grant usage on schema public to anon;
grant select, insert, update, delete on all tables in schema public to anon;
grant usage, select on all sequences in schema public to anon;

alter default privileges in schema public grant select, insert, update, delete on tables to anon;
alter default privileges in schema public grant usage, select on sequences to anon;

-- Development-only access. Do not use these policies for real resident data.
do $$
declare
  table_name text;
begin
  foreach table_name in array array['clients','staff','meals','medications','progress_notes','appointments','finance_records','policy_updates','training_records','staff_schedules'] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists "development access" on public.%I', table_name);
    execute format('create policy "development access" on public.%I for all to anon using (true) with check (true)', table_name);
  end loop;
end $$;
